name: trixor
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.0+2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  package_info: ^2.0.0
  wakelock: ^0.5.1 # https://pub.dev/packages/wakelock
  sqflite: ^2.0.0+3
  #audioplayers: ^0.19.0 # https://pub.dev/packages/audioplayers
  #assets_audio_player: ^3.0.3+1 # https://pub.dev/packages/assets_audio_player
  #assets_audio_player_web: ^3.0.3+3
  just_audio: ^0.8.0
  vibration: ^1.7.4-nullsafety.0 # https://pub.dev/packages/vibration
  shared_preferences: ^2.0.6 # https://pub.dev/packages/shared_preferences

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0 # https://pub.dev/packages/flutter_launcher_icons

flutter_icons: # flutter pub run flutter_launcher_icons:main
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "assets/iconbackground.png"
  adaptive_icon_foreground: "assets/iconforeground.png"
  remove_alpha_ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/sounds/270402__littlerobotsoundfactory__jingle-win-00.mp3
    - assets/sounds/270403__littlerobotsoundfactory__jingle-lose-00.mp3
    - assets/sounds/342750__rhodesmas__coins-purchase-4.mp3
    - assets/sounds/392183__dexus5__negative.mp3
    - assets/sounds/404743__owlstorm__retro-video-game-sfx-fail.mp3
    - assets/sounds/547564__eminyildirim__futuristic-alarm.mp3
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
